### ISSUE TITLE
Lesson notes by Hiromi Suenaga

### ISSUE THREAD

**Issue by bkowshik** [bkowshik/100-days-of-fastai#12]
Source: https://medium.com/@hiromi_suenaga

### Part 1. Practical Deep Learning for Coders
- [ ] [Lesson 1](https://medium.com/@hiromi_suenaga/deep-learning-2-part-1-lesson-1-602f73869197)
- [ ] [Lesson 2](https://medium.com/@hiromi_suenaga/deep-learning-2-part-1-lesson-2-eeae2edd2be4)
- [ ] [Lesson 3](https://medium.com/@hiromi_suenaga/deep-learning-2-part-1-lesson-3-74b0ef79e56)
- [ ] [Lesson 4](https://medium.com/@hiromi_suenaga/deep-learning-2-part-1-lesson-4-2048a26d58aa)
- [ ] [Lesson 5](https://medium.com/@hiromi_suenaga/deep-learning-2-part-1-lesson-5-dd904506bee8)
- [ ] [Lesson 6](https://medium.com/@hiromi_suenaga/deep-learning-2-part-1-lesson-6-de70d626976c)
- [ ] [Lesson 7](https://medium.com/@hiromi_suenaga/deep-learning-2-part-1-lesson-7-1b9503aff0c)

### Part 2. Cutting Edge Deep Learning for Coders
- [ ] [Lesson 8](https://medium.com/@hiromi_suenaga/deep-learning-2-part-2-lesson-8-5ae195c49493)
- [ ] [Lesson 9](https://medium.com/@hiromi_suenaga/deep-learning-2-part-2-lesson-9-5f0cf9e4bb5b)
- [ ] [Lesson 10](https://medium.com/@hiromi_suenaga/deep-learning-2-part-2-lesson-10-422d87c3340c)
- [ ] [Lesson 11](https://medium.com/@hiromi_suenaga/deep-learning-2-part-2-lesson-11-61477d24dc34)
- [ ] [Lesson 12](https://medium.com/@hiromi_suenaga/deep-learning-2-part-2-lesson-12-215dfbf04a94)

### Machine Learning for Coders
- [ ] [Lesson 1](https://medium.com/@hiromi_suenaga/machine-learning-1-lesson-1-84a1dc2b5236)
- [ ] [Lesson 2](https://medium.com/@hiromi_suenaga/machine-learning-1-lesson-2-d9aebd7dd0b0)
- [ ] [Lesson 3](https://medium.com/@hiromi_suenaga/machine-learning-1-lesson-3-fa4065d8cb1e)
