### ISSUE TITLE
Lesson notes by Tim Lee

### ISSUE THREAD

**Issue by bkowshik** [bkowshik/100-days-of-fastai#15]
### Part 1. Practical Deep Learning for Coders
- [ ] [Lesson 1](http://forums.fast.ai/t/deeplearning-lec1notes/7089)
- [ ] [Lesson 2](http://forums.fast.ai/t/deeplearning-lecnotes2/7515)
- [ ] [Lesson 3](http://forums.fast.ai/t/deeplearning-lecnotes3/7866)
- [ ] [Lesson 4](http://forums.fast.ai/t/deeplearning-lec4notes/8146)
- [ ] [Lesson 5](http://forums.fast.ai/t/deeplearning-lecnotes5/8416)
- [ ] [Lesson 6](http://forums.fast.ai/t/deeplearning-lecnotes6/8641)
- [ ] [Lesson 7](http://forums.fast.ai/t/deeplearning-lec7notes/8939)

### Part 2. Cutting Edge Deep Learning for Coders
- [ ] [Lesson 8](http://forums.fast.ai/t/deeplearning-lec8-notes/13684)
- [ ] [Lesson 9](http://forums.fast.ai/t/deeplearning-lec9-notes/14113)
- [ ] [Lesson 10](http://forums.fast.ai/t/deeplearning-lec10-notes/14658)
- [ ] [Lesson 11](http://forums.fast.ai/t/deeplearning-lec11-notes/16407)
